# Generated by Django 3.1.5 on 2021-01-28 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.CharField(max_length=64, verbose_name='사용자 ID')),
                ('userPw', models.CharField(max_length=64, verbose_name='사용자 PW')),
                ('userName', models.CharField(max_length=64, verbose_name='사용자 이름')),
                ('userAddress', models.CharField(max_length=256, verbose_name='사용자주소')),
                ('userPhone', models.CharField(max_length=64, verbose_name='사용자 전화번호')),
            ],
            options={
                'verbose_name': '개인 사용자들',
                'verbose_name_plural': '개인 사용자들',
                'db_table': 'users',
            },
        ),
    ]
