# Generated by Django 3.1.5 on 2021-01-26 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('house_no', models.CharField(max_length=32, verbose_name='집번호')),
                ('master_no', models.CharField(max_length=32, verbose_name='집주인 번호')),
                ('house_name', models.CharField(max_length=64, verbose_name='집이름')),
                ('house_location', models.CharField(max_length=256, verbose_name='집주소')),
                ('master_name', models.CharField(max_length=65, verbose_name='집주인 이름')),
            ],
            options={
                'verbose_name': '방 DB',
                'verbose_name_plural': '방 DB',
                'db_table': 'room',
            },
        ),
    ]
