# Generated by Django 3.1.5 on 2021-01-26 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='house_image',
            field=models.ImageField(blank=True, null=True, upload_to='static/img/room/'),
        ),
    ]
