# Generated by Django 3.1.5 on 2021-01-27 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0002_room_house_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='house_image',
            new_name='room_image',
        ),
        migrations.RenameField(
            model_name='room',
            old_name='house_location',
            new_name='room_location',
        ),
        migrations.RenameField(
            model_name='room',
            old_name='house_name',
            new_name='room_name',
        ),
        migrations.RenameField(
            model_name='room',
            old_name='house_no',
            new_name='room_no',
        ),
        migrations.AddField(
            model_name='room',
            name='room_detail',
            field=models.TextField(max_length=1024, null=True, verbose_name='방 정보(상세)'),
        ),
        migrations.AddField(
            model_name='room',
            name='room_detail_s',
            field=models.TextField(max_length=128, null=True, verbose_name='방 정보(짧음)'),
        ),
    ]
